repos:
-   repo: https://github.com/ambv/black
    rev: 18.6b4
    hooks:
    - id: black
-   repo: git://github.com/doublify/pre-commit-rust
    rev: 40862989fd1705e8b898e7412aa7a4762ae89a74
    hooks:
    -   id: fmt