sudo: false
language: rust
rust:
  - nightly
os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew upgrade pyenv; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cd /opt/pyenv/plugins/python-build/../.. && git pull; fi
  - pyenv install 3.7.0

install:
  - poetry install -v

script:
  - cargo test --verbose
  - poetry run pytest
