sudo: false
language: rust
rust:
  - nightly
os:
  - osx
before_install:
  - brew update && brew install python
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3.7

install:
  - poetry install -v

script:
  - cargo test --verbose
  - poetry run pytest
