sudo: false
language: rust
rust:
  - nightly
os:
  - osx
before_install:
  - brew update && brew upgrade pyenv
  - pyenv install 3.7.0
  - pyenv global 3.7.0
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | $(pyenv root)/shims/python3.7

install:
  - $(pyenv root)/shims/poetry install -v

script:
  - cargo test --verbose
  - $(pyenv root)/shims/poetry run pytest
