sudo: false
language: rust
rust:
  - nightly
os:
  - linux
  - osx

before_install:
  - git clone git://github.com/pyenv/pyenv-update.git ~/.pyenv/plugins/pyenv-update
  - pyenv update
  - pyenv install 3.7.0

install:
  - poetry install -v

script:
  - cargo test --verbose
  - poetry run pytest
