build: off
os: Visual Studio 2015
environment:
  matrix:
    - channel: nightly
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: i686-pc-windows-msvc
install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin;;C:\Python37\Scripts
  - rustc -vV
  - cargo -vV
  - C:\Python37\python.exe -m pip install -U pip
  - C:\Python37\python.exe -m pip install poetry --pre
  - C:\Python37\Scripts\poetry.exe install -v
test_script:
  - cargo test --verbose
  - C:\Python37\Scripts\poetry.exe run pytest
