{
  "version": 2,
  "jobs": {
    "build": {
      "docker": [
        {
          "image": "circleci/python:3.7-stretch"
        }
      ],
      "steps": [
        "checkout",
        {
          "restore_cache": {
            "key": "project-cache"
          }
        },
        {
          "run": {
            "name": "Install dependencies",
            "command": "\n        sudo apt update\n        sudo apt install build-essential -y\n        "
          }
        },
        {
          "run": {
            "name": "Install rust",
            "command": "\n        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly\n        echo 'export PATH=${HOME}/.cargo/bin:${PATH}' >> $BASH_ENV\n        source $BASH_ENV\n        rustup update\n        rustup install nightly\n        rustup default nightly\n        rustup component add rustfmt-preview\n        "
          }
        },
        {
          "run": {
            "name": "Install Poetry",
            "command": "curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | sudo python3.7"
          }
        },
        {
          "run": {
            "name": "Install Package",
            "command": "poetry install -v"
          }
        },
        {
          "run": {
            "name": "Check Rust Formatting",
            "command": "rustup run nightly cargo fmt -- --check"
          }
        },
        {
          "run": {
            "name": "Check Python Formatting",
            "command": "poetry run black --check src tests build.py .circleci tools"
          }
        },
        {
          "run": {
            "name": "Build Debug",
            "command": "\n        cc --version\n        rustup run nightly cargo build\n        "
          }
        },
        {
          "run": {
            "name": "Build Release",
            "command": "rustup run nightly cargo build --release"
          }
        },
        {
          "run": {
            "name": "Run Rust Tests",
            "command": "rustup run nightly cargo test"
          }
        },
        {
          "run": {
            "name": "Run Python Tests",
            "command": "poetry run pytest"
          }
        },
        {
          "save_cache": {
            "key": "project-cache",
            "paths": [
              "~/.cargo",
              "./target"
            ]
          }
        }
      ]
    }
  }
}